import { streamingPlatforms } from "@/app/lib/streaming-platforms";
import { FollowerTypeEnum, ScopeEnum } from "@/lib/types/strapi-autogenerated";
import { Box, Flex, ScrollArea, Skeleton, Stack, Text } from "@mantine/core";
import { Suspense } from "react";
import {
  fetchLatestFollowers,
  fetchRecordings,
} from "./actions/fetch-recordings";
import { DashboardHero } from "./components/dashboard-hero";
import { LatestFollowersSection } from "./components/latest-followers-section";
import { MyFeedSection } from "./components/my-feed-section";

const platformMap: Record<string, FollowerTypeEnum> = {
  TikTok: FollowerTypeEnum.Tiktok,
  Twitch: FollowerTypeEnum.Twitch,
  Kick: FollowerTypeEnum.Kick,
  YouTube: FollowerTypeEnum.Youtube,
  AfreecaTV: FollowerTypeEnum.Afreecatv,
  Pandalive: FollowerTypeEnum.Pandalive,
  Bigo: FollowerTypeEnum.Bigo,
  Tango: FollowerTypeEnum.Tango,
};

export default async function Page() {
  const followersPromise = fetchLatestFollowers();
  const myFeedPromise = fetchRecordings(ScopeEnum.Following);

  return (
    <Stack w="100%">
      <DashboardHero />

      <ScrollArea px="md" type="auto" offsetScrollbars>
        <Flex gap="sm" wrap="nowrap" justify="center">
          {streamingPlatforms.map((platform) => (
            <Stack
              key={platform.name}
              align="center"
              justify="flex-start"
              gap={8}
              px="lg"
              py="md"
              style={{
                borderRadius: "var(--mantine-radius-lg)",
                minWidth: 100,
              }}
            >
              <Box
                w={36}
                h={36}
                style={{
                  backgroundColor: "#94a3b8",
                  maskImage: `url(${platform.file})`,
                  maskSize: "contain",
                  maskRepeat: "no-repeat",
                  maskPosition: "center",
                  WebkitMaskImage: `url(${platform.file})`,
                  WebkitMaskSize: "contain",
                  WebkitMaskRepeat: "no-repeat",
                  WebkitMaskPosition: "center",
                }}
              />
              <Text size="sm" fw={600} c="#94a3b8">
                {platform.name}
              </Text>
            </Stack>
          ))}
        </Flex>
      </ScrollArea>

      <Suspense fallback={<Skeleton h={220} radius="md" m="md" />}>
        <LatestFollowersSection followersPromise={followersPromise} />
      </Suspense>

      <Suspense fallback={<Skeleton h={360} radius="md" m="md" />}>
        <MyFeedSection myFeedPromise={myFeedPromise} />
      </Suspense>
    </Stack>
  );
}
