import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import { Skeleton, Stack } from "@mantine/core";
import { Suspense } from "react";
import {
  fetchLatestFollowers,
  fetchRecordings,
} from "./actions/fetch-recordings";
import { DashboardHero } from "./components/dashboard-hero";
import { DiscoverSection } from "./components/discover-section";
import { LatestFollowersSection } from "./components/latest-followers-section";
import { MyFeedSection } from "./components/my-feed-section";
import { UnpauseFollowers } from "./components/unpause-followers";

export default async function Page() {
  const followersPromise = fetchLatestFollowers();
  const myFeedPromise = fetchRecordings(ScopeEnum.Following);
  const discoverPromise = fetchRecordings(ScopeEnum.Discover);

  return (
    <Stack w="100%" gap="xl">
      <UnpauseFollowers />

      <DashboardHero />

      <Suspense fallback={<Skeleton h={120} radius="md" />}>
        <LatestFollowersSection followersPromise={followersPromise} />
      </Suspense>

      <Suspense fallback={<Skeleton h={360} radius="md" />}>
        <MyFeedSection myFeedPromise={myFeedPromise} />
      </Suspense>

      <Suspense fallback={<Skeleton h={360} radius="md" />}>
        <DiscoverSection discoverPromise={discoverPromise} />
      </Suspense>
    </Stack>
  );
}
