import { CountryFlag } from "@/app/[locale]/(protected)/components/country-flag";
import FollowButton from "@/app/[locale]/(protected)/components/follow-button";
import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import UnfollowButton from "@/app/[locale]/(protected)/components/unfollow-button";
import OpenSocial from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { safeRelativeTime } from "@/app/lib/safe-relative-time";
import { Role } from "@/app/providers/ability-provider";
import { Follower } from "@/lib/types/strapi-autogenerated";
import {
  Alert,
  Avatar,
  Box,
  Flex,
  Group,
  Paper,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { IconCalendarPlus, IconPlayerPause, IconRefresh } from "@tabler/icons-react";
import { getFormatter, getTranslations } from "next-intl/server";
import Image from "next/image";
import { AdminMenu } from "./admin-menu";
import { ProfileTabs } from "./profile-tabs";

interface ProfileHeaderProps {
  follower: Follower & { isFollowing: boolean };
  isRecording?: boolean;
}

export async function ProfileHeader({
  follower,
  isRecording = false,
}: ProfileHeaderProps) {
  const t = await getTranslations("protected.profile");
  const format = await getFormatter();

  return (
    <Stack mb="md" gap="md">
      <Paper
        radius="lg"
        p={{ base: "md", sm: "xl" }}
        style={{
          background:
            "linear-gradient(160deg, rgba(16, 185, 129, 0.12) 0%, rgba(6, 95, 70, 0.06) 100%)",
          border: "1px solid rgba(16, 185, 129, 0.15)",
        }}
      >
        <Flex
          direction={{ base: "column", sm: "row" }}
          align={{ base: "center", sm: "flex-start" }}
          gap="lg"
        >
          <Box pos="relative" style={{ flexShrink: 0 }}>
            <Avatar
              size={110}
              radius="xl"
              style={{
                border: isRecording
                  ? "3px solid red"
                  : "3px solid rgba(16, 185, 129, 0.4)",
                boxShadow: isRecording
                  ? "0 0 20px rgba(255, 0, 0, 0.3)"
                  : "0 4px 24px rgba(0, 0, 0, 0.25)",
              }}
            >
              {follower.avatar?.url && (
                <Image
                  src={generateAvatarUrl(follower.avatar?.url)}
                  alt={follower.username || "Avatar"}
                  width={110}
                  height={110}
                />
              )}
            </Avatar>

            {follower.type && (
              <FollowerTypeIcon
                pos="absolute"
                bottom={-2}
                right={-2}
                color="transparent"
                type={follower.type}
                size={32}
              />
            )}
          </Box>

          <Stack gap={6} style={{ flex: 1 }}>
            <Group gap="xs">
              <Title order={2}>{decodeURIComponent(follower.username)}</Title>
              {follower.countryCode && (
                <CountryFlag countryCode={follower.countryCode} size={26} />
              )}
            </Group>

            <Group gap="xs">
              <Group gap={4}>
                <IconCalendarPlus size={13} color="var(--mantine-color-dimmed)" />
                <Text size="xs" c="dimmed" suppressHydrationWarning>
                  {t("addedAgo", {
                    time: safeRelativeTime(format, follower.createdAt),
                  })}
                </Text>
              </Group>
              {follower.lastCheckedAt && (
                <Group gap={4}>
                  <IconRefresh size={13} color="var(--mantine-color-dimmed)" />
                  <Text size="xs" c="dimmed" suppressHydrationWarning>
                    {t("lastCheckedAgo", {
                      time: safeRelativeTime(format, follower.lastCheckedAt),
                    })}
                  </Text>
                </Group>
              )}
            </Group>

            <Group gap="xs" mt={4}>
              <OpenSocial follower={follower} />
              {follower.isFollowing ? (
                <UnfollowButton
                  username={follower.username!}
                  type={follower.type}
                />
              ) : (
                <FollowButton
                  username={follower.username!}
                  type={follower.type}
                />
              )}
              <AdminMenu follower={follower} />
            </Group>
          </Stack>
        </Flex>
      </Paper>

      {follower.pause && !follower.isFollowing && (
        <Role is="authenticated" not>
          <Alert
            icon={<IconPlayerPause size={20} />}
            color="yellow"
            variant="light"
          >
            {t("paused")}
          </Alert>
        </Role>
      )}

      <ProfileTabs type={follower.type!} username={follower.username!} />
    </Stack>
  );
}
