import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";

import { Clip, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { getLocale } from "next-intl/server";
import { ClipPlayer } from "./clip-player";

interface Props {
  clip: Clip;
  type: FollowerTypeEnum;
}

export async function ImageClipPreview({ clip, type }: Props) {
  const locale = await getLocale();

  return (
    <div
      style={{
        position: "relative",
        overflow: "hidden",
      }}
    >
      <ClipPlayer
        previewUrl={`/clip/${clip.documentId}/thumbnail.jpg`}
        src={`/clip/${clip.documentId}/clip.mp4`}
        subtitlesUrl={`/clip/${clip.documentId}/subtitles.vtt?locale=${locale}`}
        locale={locale}
      />

      <FollowerTypeIcon
        type={type}
        color="black"
        opacity={0.8}
        pos="absolute"
        top={20}
        right={18}
        style={{
          pointerEvents: "none",
        }}
      />
    </div>
  );
}
