"use client";

import { useWatched } from "@/app/hooks/use-watched";
import { getImageUrl } from "@/app/lib/media-url";
import { configureHls } from "@/lib/configure-hls";
import { Recording } from "@/lib/types/strapi-autogenerated";
import "hls-video-element";
import type { HlsVideoElement } from "hls-video-element";
import "media-chrome";
import "@player.style/demuxed-2022";
import { usePathname, useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { HlsVideo, MediaPosterImage } from "./media-chrome";

configureHls();
interface VideoPlayerProps {
  recording: Recording;
  defaultMuted?: boolean;
  onMuteChange?: (muted: boolean) => void;
  autoPlay?: boolean;
  onPlay?: () => void;
}

export function VideoPlayer({
  recording,
  defaultMuted = true,
  onMuteChange,
  autoPlay = false,
  onPlay,
}: VideoPlayerProps) {
  const searchParams = useSearchParams();
  const startTime = Number(searchParams.get("t")) || 0;

  const controllerRef = useRef<HTMLElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [initialAutoPlay] = useState(autoPlay);

  // Destroy HLS on unmount (scroll away kills VideoPlayer via VideoSlide)
  useEffect(() => {
    const controller = controllerRef.current;
    return () => {
      if (!controller) return;
      const hlsEl = controller.querySelector(
        "hls-video",
      ) as HlsVideoElement | null;
      if (!hlsEl) return;

      hlsEl.pause();
      if (hlsEl.api) {
        hlsEl.api.stopLoad();
        hlsEl.api.detachMedia();
        hlsEl.api.destroy();
        hlsEl.api = null;
      }
    };
  }, [recording.documentId]);

  // Stop hls loader when URL navigates away from this video.
  // Next.js parallel @modal routes don't unmount on nav (next.js#62430).
  const pathname = usePathname();
  useEffect(() => {
    if (!recording.documentId) return;
    if (pathname.includes(recording.documentId)) return;
    const controller = controllerRef.current;
    if (!controller) return;
    const hlsEl = controller.querySelector(
      "hls-video",
    ) as HlsVideoElement | null;
    if (!hlsEl?.api) return;
    hlsEl.api.stopLoad();
  }, [pathname, recording.documentId]);

  // Hide PiP button inside shadow DOM
  useEffect(() => {
    const el = controllerRef.current;
    if (!el) return;
    const tryHide = () => {
      const style = document.createElement("style");
      style.textContent = "media-pip-button { display: none !important; }";
      el.shadowRoot?.appendChild(style);
    };
    tryHide();
    const timer = setTimeout(tryHide, 500);
    return () => clearTimeout(timer);
  }, []);

  // Handle seek to start time
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !startTime) return;

    const handleLoaded = () => {
      video.currentTime = startTime;
    };

    video.addEventListener("loadedmetadata", handleLoaded, { once: true });

    return () => {
      video.removeEventListener("loadedmetadata", handleLoaded);
    };
  }, [startTime]);

  // Notify parent on first play (unlocks autoplay for subsequent videos)
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !onPlay) return;

    const handlePlay = () => onPlay();
    video.addEventListener("play", handlePlay, { once: true });
    return () => video.removeEventListener("play", handlePlay);
  }, [onPlay]);

  // Mark as WATCHED in localStorage after 1.5s of actual playback.
  const { markWatched } = useWatched();
  useEffect(() => {
    const video = videoRef.current;
    const id = recording.documentId;
    if (!video || !id) return;
    let timer: ReturnType<typeof setTimeout> | null = null;
    const start = () => {
      if (timer) return;
      timer = setTimeout(() => markWatched(id), 1500);
    };
    const stop = () => {
      if (timer) {
        clearTimeout(timer);
        timer = null;
      }
    };
    video.addEventListener("playing", start);
    video.addEventListener("pause", stop);
    video.addEventListener("waiting", stop);
    return () => {
      stop();
      video.removeEventListener("playing", start);
      video.removeEventListener("pause", stop);
      video.removeEventListener("waiting", stop);
    };
  }, [recording.documentId, markWatched]);

  // Swallow autoplay rejections. NotAllowedError = unmuted autoplay
  // blocked → retry muted. AbortError = play() interrupted by pause()
  // (rapid scroll race) → ignore.
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    const tryPlay = () => {
      const p = video.play();
      if (p && typeof p.catch === "function") {
        p.catch((err: DOMException) => {
          if (err?.name === "NotAllowedError" && !video.muted) {
            video.muted = true;
            video.play().catch(() => {});
          }
        });
      }
    };
    if (initialAutoPlay) {
      if (video.readyState >= 2) tryPlay();
      else video.addEventListener("loadeddata", tryPlay, { once: true });
    }
    return () => video.removeEventListener("loadeddata", tryPlay);
  }, [initialAutoPlay]);

  // Track mute changes
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !onMuteChange) return;

    const handleVolumeChange = () => {
      onMuteChange(video.muted);
    };

    video.addEventListener("volumechange", handleVolumeChange);
    return () => video.removeEventListener("volumechange", handleVolumeChange);
  }, [onMuteChange]);

  const handleDoubleClick = () => {
    const controller = controllerRef.current;
    if (!controller) return;

    if (document.fullscreenElement) {
      document.exitFullscreen();
    } else {
      const el = controller as HTMLElement & {
        webkitRequestFullscreen?: () => Promise<void>;
      };
      if (el.requestFullscreen) {
        el.requestFullscreen();
      } else if (el.webkitRequestFullscreen) {
        el.webkitRequestFullscreen();
      }
    }
  };

  return (
    <>
    {/* @ts-expect-error - web component */}
    <media-theme-demuxed-2022
      ref={controllerRef}
      onDoubleClick={handleDoubleClick}
      style={{
        width: "100%",
        height: "75vh",
      }}
    >
      <HlsVideo
        ref={videoRef}
        src={`/video/${recording.documentId}/playlist.m3u8`}
        slot="media"
        crossOrigin="anonymous"
        playsInline
        autoPlay={initialAutoPlay || undefined}
        preload={initialAutoPlay ? undefined : "none"}
        muted={defaultMuted}
      >
        {typeof window !== "undefined" &&
          window.matchMedia("(pointer: fine)").matches && (
            <track
              default
              kind="metadata"
              label="thumbnails"
              src={`/video/${recording.documentId}/thumbnails.vtt`}
            />
          )}
      </HlsVideo>

      <MediaPosterImage
        slot="poster"
        src={getImageUrl(recording.documentId!, "screenshot.jpg", recording.sources?.at(-1))}
      />
    {/* @ts-expect-error - web component */}
    </media-theme-demuxed-2022>
    </>
  );
}
