"use client";

import type { HlsVideoElement } from "hls-video-element";
import { Recording } from "@/lib/types/strapi-autogenerated";
import { Flex, Loader, Modal } from "@mantine/core";
import { useRouter } from "next/navigation";
import { useCallback } from "react";
import { VideoPlayer } from "./video-player";

interface VideoModalProps {
  recording: Recording | undefined | null;
  isLoading?: boolean;
  fallbackUrl?: string;
  accessDenied?: React.ReactNode;
}

export function VideoModal({
  recording,
  isLoading,
  fallbackUrl,
  accessDenied,
}: VideoModalProps) {
  const router = useRouter();

  const handleClose = useCallback(() => {
    document.querySelectorAll<HlsVideoElement>("hls-video").forEach((el) => {
      el.pause();
      if (el.api) {
        el.api.stopLoad();
        el.api.detachMedia();
        el.api.destroy();
        el.api = null;
      }
    });
    setTimeout(() => router.back(), 50);
  }, [router]);

  if (isLoading) {
    return (
      <Modal opened={true} onClose={handleClose} size="xl" centered>
        <Flex h={400} justify="center" align="center">
          <Loader size="lg" />
        </Flex>
      </Modal>
    );
  }

  if (accessDenied) {
    return <>{accessDenied}</>;
  }

  if (!recording) {
    if (fallbackUrl) router.replace(fallbackUrl);
    return null;
  }

  return (
    <Modal opened={true} onClose={handleClose} size="xl" centered>
      <VideoPlayer
        recording={recording}
        defaultMuted={false}
        autoPlay={true}
      />
    </Modal>
  );
}
