import publicApi from "@/lib/public-api";
import { SubscriptionStatusEnum } from "@/lib/types/strapi-autogenerated";
import createMollieClient from "@mollie/api-client";
import { NextRequest, NextResponse } from "next/server";
import { getRoleIdByName, updateUserSubscription } from "../../freemius/utils";

const mollieClient = createMollieClient({
  apiKey: process.env.MOLLIE_API_KEY!,
});

function findUserByMollieCustomerId(customerId: string) {
  return publicApi.usersPermissionsUsersRoles
    .usersList({
      query: {
        filters: {
          mollie: {
            $contains: `"customerId":${JSON.stringify(customerId)}`,
          },
        },
      },
    } as never)
    .then((r) => r.data?.[0] || null)
    .catch(() => null);
}

function calculateEndDate(interval: string): string {
  const now = new Date();
  switch (interval) {
    case "1 month":
      now.setMonth(now.getMonth() + 1);
      break;
    case "3 months":
      now.setMonth(now.getMonth() + 3);
      break;
    case "12 months":
      now.setFullYear(now.getFullYear() + 1);
      break;
    default:
      now.setMonth(now.getMonth() + 1);
  }
  return now.toISOString();
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.formData();
    const paymentId = body.get("id") as string;

    if (!paymentId) {
      return NextResponse.json({ error: "Missing id" }, { status: 400 });
    }

    const payment = await mollieClient.payments.get(paymentId);

    console.log(
      `[mollie-webhook] payment ${paymentId} status=${payment.status} seq=${payment.sequenceType}`,
    );

    const customerId = payment.customerId;
    const metadata = payment.metadata as {
      userId?: string;
      billingCycle?: string;
      interval?: string;
    } | null;

    // Handle first payment completion — create subscription
    if (
      payment.status === "paid" &&
      payment.sequenceType === "first" &&
      customerId
    ) {
      const billingCycle = metadata?.billingCycle || "monthly";
      const interval = metadata?.interval || "1 month";
      const userId = metadata?.userId;

      const prices: Record<string, string> = {
        monthly: "15.00",
        quarterly: "30.00",
        annual: "96.00",
      };

      const baseUrl =
        process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";

      const subscription = await mollieClient.customerSubscriptions.create({
        customerId,
        amount: { currency: "USD", value: prices[billingCycle] || "15.00" },
        interval,
        description: `StreamArchive Premium - ${billingCycle}`,
        webhookUrl: `${baseUrl}/api/mollie/webhook`,
      });

      const premiumRoleId = await getRoleIdByName("premium");
      const subscriptionEndDate = calculateEndDate(interval);

      if (userId) {
        await publicApi.usersPermissionsUsersRoles.usersUpdate(
          { id: userId },
          {
            role: premiumRoleId || undefined,
            subscriptionStatus: "active",
            subscriptionEndDate,
            billingPeriod: billingCycle,
            paymentProvider: "mollie",
            mollie: JSON.stringify({
              customerId,
              subscriptionId: subscription.id,
              paymentId,
            }),
          } as never,
        );
      }

      console.log(
        `[mollie-webhook] user ${userId} upgraded to premium (${billingCycle})`,
      );
      return NextResponse.json({ received: true });
    }

    // Handle recurring payment success
    if (payment.status === "paid" && payment.sequenceType === "recurring") {
      if (customerId) {
        const user = await findUserByMollieCustomerId(customerId);
        if (user?.id) {
          const interval = metadata?.interval || "1 month";
          await updateUserSubscription(user.id.toString(), {
            subscriptionStatus: SubscriptionStatusEnum.Active,
            subscriptionEndDate: calculateEndDate(interval),
          });
          console.log(`[mollie-webhook] user ${user.id} subscription renewed`);
        }
      }
      return NextResponse.json({ received: true });
    }

    // Handle payment failure
    if (payment.status === "failed" || payment.status === "expired") {
      if (customerId) {
        const user = await findUserByMollieCustomerId(customerId);
        if (user?.id) {
          await updateUserSubscription(user.id.toString(), {
            subscriptionStatus: SubscriptionStatusEnum.Cancelled,
          });
          console.log(
            `[mollie-webhook] user ${user.id} payment ${payment.status}`,
          );
        }
      }
      return NextResponse.json({ received: true });
    }

    return NextResponse.json({ received: true });
  } catch (error) {
    console.error("[mollie-webhook] error:", error);
    return NextResponse.json(
      { error: "Webhook processing failed" },
      { status: 500 },
    );
  }
}
