"use client";

import { trackEvent } from "@/app/lib/analytics";
import { useRole } from "@/app/providers/ability-provider";
import { useUser } from "@/app/providers/user-provider";
import { GetUsersPermissionsUsersRolesData } from "@/lib/types/strapi-autogenerated";
import {
  Alert,
  Anchor,
  Badge,
  Button,
  Card,
  Flex,
  Grid,
  GridCol,
  Group,
  Modal,
  Paper,
  SegmentedControl,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import {
  IconBell,
  IconBrandApple,
  IconBrandMastercard,
  IconBrandPaypal,
  IconBrandVisa,
  IconCheck,
  IconDownload,
  IconHeadset,
  IconScissors,
  IconStar,
  IconUsers,
  IconVideo,
} from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { cancelSubscription } from "./actions";
import { MolliePaymentButton } from "./components/mollie-payment-button";

// Extend user type with subscription fields from schema
type UserWithSubscription = GetUsersPermissionsUsersRolesData & {
  subscriptionStatus?: "active" | "cancelled" | "expired";
  subscriptionEndDate?: string;
  billingPeriod?: string;
};

export default function PremiumClient({
  paymentError,
}: {
  paymentError?: string;
}) {
  const t = useTranslations("protected.premium");
  const [selectedBilling, setSelectedBilling] = useState("12months");
  const selectedPayment = "mollie";

  const user = useUser() as UserWithSubscription | null;
  const role = useRole();
  const router = useRouter();
  const [
    cancelModalOpened,
    { open: openCancelModal, close: closeCancelModal },
  ] = useDisclosure(false);
  const [cancelling, setCancelling] = useState(false);

  const BILLING_OPTIONS = [
    {
      id: "1month",
      label: t("billing1MonthLabel"),
      price: 15,
      perMonth: 15,
      savings: null,
      badge: null,
      billingCycle: "monthly" as const,
      stripeOnly: false,
    },
    {
      id: "3months",
      label: t("billing3MonthsLabel"),
      price: 30,
      perMonth: 10,
      savings: t("billing3MonthsSavings"),
      badge: null,
      billingCycle: "quarterly" as const,
      stripeOnly: true,
    },
    {
      id: "12months",
      label: t("billing12MonthsLabel"),
      price: 96,
      perMonth: 8,
      savings: t("billing12MonthsSavings"),
      badge: t("billing12MonthsBadge"),
      billingCycle: "annual" as const,
      stripeOnly: false,
    },
  ];

  const filteredBillingOptions = BILLING_OPTIONS;

  const PREMIUM_FEATURES = [
    { icon: IconUsers, label: t("premiumRecord100"), color: "#52FF94" },
    { icon: IconDownload, label: t("premiumFullControl"), color: "#34d399" },
    { icon: IconBell, label: t("premiumNotifications"), color: "#6ee7b7" },
    { icon: IconScissors, label: t("premiumClipEditor"), color: "#a7f3d0" },
    { icon: IconVideo, label: t("premiumWatchLater"), color: "#52FF94" },
    {
      icon: IconDownload,
      label: t("premiumDownloadRecordings"),
      color: "#34d399",
    },
    { icon: IconHeadset, label: t("premiumPrioritySupport"), color: "#6ee7b7" },
  ];

  const selectedPlan = filteredBillingOptions.find(
    (o) => o.id === selectedBilling,
  );

  // Translate billing period
  const getTranslatedBillingPeriod = (period?: string) => {
    switch (period) {
      case "monthly":
        return t("billingPeriodMonthly");
      case "quarterly":
        return t("billingPeriodQuarterly");
      case "annual":
        return t("billingPeriodAnnual");
      case "lifetime":
        return t("billingPeriodLifetime");
      default:
        return period || "";
    }
  };

  // Determine if user is premium (admin, champion, or has active/cancelled subscription)
  const isPremiumRole = role?.type === "admin" || role?.type === "champion";
  const hasActiveSubscription =
    user?.subscriptionStatus === "active" ||
    user?.subscriptionStatus === "cancelled";
  const isPremium = isPremiumRole || hasActiveSubscription;
  const canCancel =
    user?.subscriptionStatus === "active" &&
    !isPremiumRole &&
    user?.billingPeriod !== "lifetime";

  const handlePlanSelect = (planId: string) => {
    const plan = BILLING_OPTIONS.find((o) => o.id === planId);
    if (plan && planId !== selectedBilling) {
      trackEvent("premium_plan_selected", {
        plan: plan.label,
        billing_cycle: plan.billingCycle,
        price: plan.price,
      });
    }
    setSelectedBilling(planId);
  };

  const handleCancelSubscription = async () => {
    setCancelling(true);
    const result = await cancelSubscription();
    setCancelling(false);

    if (result.success) {
      closeCancelModal();
      router.refresh();
    } else {
      console.error("Failed to cancel:", result.error);
    }
  };

  return (
    <Stack w="100%" maw={600} mx="auto">
      {paymentError && (
        <Alert color="red" variant="light" withCloseButton>
          <Text size="sm">
            {paymentError === "Payment failed"
              ? t("paymentFailed")
              : paymentError === "Payment open"
                ? t("paymentCancelled")
                : paymentError === "Payment expired"
                  ? t("paymentExpired")
                  : t("paymentError")}
          </Text>
        </Alert>
      )}

      {/* Hero */}
      <Stack align="center" gap={4} pb="xl">
        <Paper
          radius="xl"
          px="md"
          py={6}
          style={{
            background: "rgba(27, 147, 69, 0.15)",
            border: "1px solid rgba(82, 255, 148, 0.3)",
          }}
        >
          <Group gap={8}>
            <IconStar size={18} color="#fbbf24" />
            <Text size="sm" fw={600} c="#52FF94">
              {t("title")}
            </Text>
          </Group>
        </Paper>

        <Title
          order={2}
          ta="center"
          style={{
            fontSize: "clamp(1.8rem, 5vw, 2.4rem)",
            fontWeight: 700,
            letterSpacing: "-0.03em",
            background: "linear-gradient(135deg, #54ff5b, #b7ff6b)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
          }}
        >
          {isPremium ? t("yourPremiumFeatures") : t("unlockPremiumFeatures")}
        </Title>

        <Text size="sm" c="dimmed" ta="center" maw={400}>
          {isPremium ? t("descriptionPremium") : t("descriptionNonPremium")}
        </Text>
      </Stack>

      {/* Premium user: current plan info */}
      {isPremium && (
        <Card
          padding="lg"
          radius="md"
          withBorder
          style={{
            background:
              "linear-gradient(135deg, rgba(27, 147, 69, 0.15) 0%, rgba(22, 163, 74, 0.08) 100%)",
            borderColor: "rgba(82, 255, 148, 0.3)",
          }}
        >
          <Stack gap="md">
            <Group gap="xs">
              <IconStar size={20} color="#fbbf24" />
              <Text fw={600} size="lg">
                {isPremiumRole ? role?.name : t("title")}
              </Text>
              {user?.subscriptionStatus === "cancelled" && (
                <Badge size="sm" variant="light" color="orange">
                  {t("cancelled")}
                </Badge>
              )}
            </Group>

            <Alert color="green" variant="light">
              <Text size="sm">
                {isPremiumRole
                  ? t("adminAccess")
                  : user?.subscriptionStatus === "cancelled"
                    ? t("cancelledMessage", {
                        billingPeriod: getTranslatedBillingPeriod(
                          user?.billingPeriod,
                        ),
                        endDate: new Date(
                          user.subscriptionEndDate!,
                        ).toLocaleDateString("en-GB"),
                      })
                    : user?.billingPeriod === "lifetime"
                      ? t("lifetimeMessage")
                      : t("activeMessage", {
                          billingPeriod: getTranslatedBillingPeriod(
                            user?.billingPeriod,
                          ),
                          renewDate: new Date(
                            user?.subscriptionEndDate || "",
                          ).toLocaleDateString("en-GB"),
                        })}
              </Text>
            </Alert>

            {canCancel && (
              <Button
                variant="subtle"
                color="gray"
                size="xs"
                onClick={openCancelModal}
              >
                {t("cancelSubscription")}
              </Button>
            )}
          </Stack>
        </Card>
      )}

      {/* Features checklist */}
      <Grid gutter="sm">
        {PREMIUM_FEATURES.map((feature) => (
          <GridCol span={6} key={feature.label}>
            <Group gap="xs" wrap="nowrap">
              <IconCheck size={16} color="#52FF94" />
              <Text size="sm">{feature.label}</Text>
            </Group>
          </GridCol>
        ))}
      </Grid>

      <Text size="xs" c="dimmed" ta="center">
        {t("futureFeatures")}{" "}
        <Anchor href="/changelog" size="xs">
          {t("seeWhatsNew")}
        </Anchor>
      </Text>

      {/* Non-premium: pricing + payment */}
      {!isPremium && (
        <>
          {/* Billing toggle */}
          <SegmentedControl
            fullWidth
            value={selectedBilling}
            onChange={handlePlanSelect}
            data={filteredBillingOptions.map((option) => ({
              value: option.id,
              label: (
                <Stack gap={0} align="center">
                  <Group gap={4}>
                    <Text size="sm" fw={600}>
                      {option.label}
                    </Text>
                    {option.badge && (
                      <Badge size="xs" variant="filled" color="green">
                        {option.badge}
                      </Badge>
                    )}
                  </Group>
                  <Text size="xs" c="dimmed">
                    ${option.perMonth}/mo
                  </Text>
                </Stack>
              ),
            }))}
            styles={{
              root: {
                background: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(82, 255, 148, 0.15)",
                borderRadius: "var(--mantine-radius-md)",
              },
              label: {
                padding: "var(--mantine-spacing-sm) var(--mantine-spacing-xs)",
              },
              indicator: {
                background: "rgba(27, 147, 69, 0.2)",
                borderRadius: "var(--mantine-radius-sm)",
              },
            }}
          />

          {/* Price display */}
          <Stack align="center" gap={0}>
            <Group gap={4} align="baseline">
              <Text
                fw={700}
                style={{
                  fontSize: "3rem",
                  letterSpacing: "-0.03em",
                  color: "#52FF94",
                }}
              >
                ${selectedPlan?.perMonth}
              </Text>
              <Text size="lg" c="dimmed">
                /mo
              </Text>
            </Group>
            {selectedPlan?.savings && (
              <Text size="sm" c="green">
                {selectedPlan.savings}
              </Text>
            )}
            {selectedPlan && selectedPlan.price !== selectedPlan.perMonth && (
              <Text size="xs" c="dimmed">
                ${selectedPlan.price} {t("total").toLowerCase()}
              </Text>
            )}
          </Stack>

          {/* Payment method icons */}
          <Group gap="xs" justify="center" wrap="wrap">
            <IconBrandVisa size={28} stroke={1.2} color="#94a3b8" />
            <IconBrandMastercard size={28} stroke={1.2} color="#94a3b8" />
            <IconBrandApple size={28} stroke={1.2} color="#94a3b8" />
            <IconBrandPaypal size={28} stroke={1.2} color="#94a3b8" />
          </Group>

          {/* CTA Button */}
          <MolliePaymentButton
            billingCycle={selectedPlan?.billingCycle || "annual"}
            planLabel={selectedPlan?.label || "Premium"}
            fullWidth
            size="lg"
            radius="xl"
            style={{
              background: "linear-gradient(135deg, #22c55e 0%, #16a34a 100%)",
            }}
          >
            {t("subscribe")}
          </MolliePaymentButton>

          <Flex gap="xs" align="center" justify="center">
            <IconCheck size={14} color="var(--mantine-color-green-6)" />
            <Text size="xs" c="dimmed">
              {t("securePayment")}
            </Text>
          </Flex>

          <Text size="xs" c="dimmed" ta="center">
            {t("vatNotice")}
          </Text>
        </>
      )}

      {/* Cancel Subscription Modal */}
      <Modal
        opened={cancelModalOpened}
        onClose={closeCancelModal}
        title={t("cancelModalTitle")}
        centered
      >
        <Stack gap="md">
          <Text size="sm">
            {t("cancelModalMessage", {
              endDate: user?.subscriptionEndDate
                ? new Date(user.subscriptionEndDate).toLocaleDateString("en-GB")
                : "",
            })}
          </Text>
          <Text size="sm" c="dimmed">
            {t("cancelModalAfter")}
          </Text>
          <Group justify="flex-end" mt="md">
            <Button variant="default" onClick={closeCancelModal}>
              {t("keepSubscription")}
            </Button>
            <Button
              color="red"
              onClick={handleCancelSubscription}
              loading={cancelling}
            >
              {t("yesCancel")}
            </Button>
          </Group>
        </Stack>
      </Modal>
    </Stack>
  );
}
