"use client";

import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { FollowerTypeEnum, Recording } from "@/lib/types/strapi-autogenerated";
import { Anchor, Avatar, Group, Stack, Text } from "@mantine/core";
import { useFormatter } from "next-intl";
import Image from "next/image";
import Link from "next/link";
import { getProfileUrl } from "../../../../components/open-social";
import { ImageSpritePreview } from "../../components/image-sprite-preview";
import { RecordingMenu } from "../../components/recording-menu";

interface Props {
  recording: Recording;
}

export default function RecordingItem({ recording }: Props) {
  const format = useFormatter();

  return (
    <Stack gap={4}>
      {recording.follower && (
        <ImageSpritePreview
          username={recording.follower?.username || "unknown"}
          type={recording.follower?.type || FollowerTypeEnum.Tiktok}
          recording={recording}
        />
      )}
      <Group gap={4} wrap="nowrap" justify="space-between">
        <Anchor
          component={Link}
          href={getProfileUrl(recording.follower)}
          style={{ flexShrink: 0 }}
        >
          <Avatar size={24}>
            {recording.follower?.avatar?.url && (
              <Image
                src={generateAvatarUrl(recording.follower?.avatar?.url)}
                alt={"Avatar"}
                width={24}
                height={24}
              />
            )}
          </Avatar>
        </Anchor>
        <Stack gap={0} style={{ flex: 1, overflow: "hidden" }}>
          <Anchor
            component={Link}
            href={getProfileUrl(recording.follower)}
            size="xs"
            truncate
          >
            {recording.follower?.username}
          </Anchor>
          <Text size="xs" c="dimmed" truncate suppressHydrationWarning>
            {format.dateTime(new Date(recording.updatedAt || ""), {
              dateStyle: "short",
            })}
          </Text>
        </Stack>
        <RecordingMenu
          recording={recording}
          username={recording.follower?.username}
          type={recording.follower?.type}
        />
      </Group>
    </Stack>
  );
}
