import { Role } from "@/app/providers/ability-provider";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import { Anchor, Stack, Tabs, TabsList, TabsTab } from "@mantine/core";
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from "@tanstack/react-query";
import { getTranslations } from "next-intl/server";
import { fetchLiveRecordings } from "./actions/fetch-live-recordings";
import LiveInfinity from "./components/live-infinity";

interface PageProps {
  searchParams: Promise<{
    scope?: string;
  }>;
}

export default async function LivePage({ searchParams }: PageProps) {
  const t = await getTranslations("protected.live");
  const { scope = ScopeEnum.Following } = await searchParams;

  const queryClient = new QueryClient();

  await queryClient.prefetchInfiniteQuery({
    queryKey: ["live-recordings", scope],
    queryFn: ({ pageParam }) => fetchLiveRecordings(scope, pageParam),
    initialPageParam: 1,
  });

  const isAll = scope === "all";

  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      <Stack w="100%">
        <Tabs
          value={isAll ? "showAll" : "default"}
          styles={{
            list: {
              borderBottomWidth: 4,
            },
            tab: {
              fontSize: "var(--mantine-font-size-lg)",
              fontWeight: 600,
              padding: "var(--mantine-spacing-sm) var(--mantine-spacing-md)",
              borderBottomWidth: 4,
            },
          }}
        >
          <TabsList>
            <TabsTab value="default">{t("title")}</TabsTab>
            <Role is={["admin", "moderator"]}>
              <TabsTab value="showAll" ml="auto">
                <Anchor href="/live?scope=all" underline="never" c="inherit">
                  {t("showAll")}
                </Anchor>
              </TabsTab>
            </Role>
          </TabsList>
        </Tabs>

        <LiveInfinity scope={scope} />
      </Stack>
    </HydrationBoundary>
  );
}
