"use server";

import api from "@/lib/api";
import publicApi from "@/lib/public-api";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import { cache } from "react";

const getUserFollowingIds = cache(async () => {
  const response =
    await api.usersPermissionsUsersRoles.getUsersPermissionsUsersRoles({
      populate: { followers: { fields: ["id"] } },
    });
  return (response.data?.followers?.map((f: any) => f.id) || []).sort();
});

export async function fetchLiveRecordings(
  scope: string = ScopeEnum.Following,
  page: number = 1,
) {
  const followingIds = await getUserFollowingIds();

  let followerFilter: object | null = null;
  if (scope === "following") {
    followerFilter = {
      id: { $in: followingIds.length > 0 ? followingIds : [0] },
    };
  } else if (scope === "discover" && followingIds.length > 0) {
    followerFilter = { id: { $notIn: followingIds } };
  }

  const response = await publicApi.recording.searchRecordings({
    pagination: { page, pageSize: 10, withCount: true },
    sort: "updatedAt:desc",
    filters: {
      sources: { state: { $eq: "recording" } },
      ...(followerFilter ? { follower: followerFilter } : {}),
    },
    populate: {
      sources: {
        filters: { state: { $eq: "recording" } },
      },
      follower: {
        fields: ["username", "type"],
        populate: { avatar: { fields: ["url"] } },
      },
    },
  });

  return {
    data: response.data?.data || [],
    meta: response.data?.meta,
  };
}
