"use server";

import api from "@/lib/api";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";

const basePopulate = {
  sources: {
    fields: ["*"],
    filters: {
      state: {
        $eq: "done",
      },
    },
  },
  follower: {
    fields: ["username", "type"],
    populate: {
      avatar: {
        fields: ["url"],
      },
    },
  },
};

const baseFilters = {
  sources: {
    state: {
      $eq: ["done"],
    },
  },
};

export async function fetchRecordings(scope: ScopeEnum) {
  const response = await api.recording.browseRecordings({
    scope,
    filters: {
      ...baseFilters,
    },
    populate: basePopulate,
    sort: "updatedAt:desc",
    "pagination[page]": 1,
    "pagination[pageSize]": 16,
  });

  return response.data?.data || [];
}

export async function fetchLatestFollowers() {
  const response = await api.follower.getFollowers({
    sort: "createdAt:desc",
    "pagination[page]": 1,
    "pagination[pageSize]": 16,
    populate: ["avatar"],
  });

  return response.data?.data || [];
}
