"use server";

import {
  fetchCachedRecordings,
  RecordingScope,
} from "@/app/actions/recordings";
import api from "@/lib/api";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";

export async function fetchRecordings(scope: ScopeEnum) {
  const result = await fetchCachedRecordings({
    scope: scope as unknown as RecordingScope,
    filters: {},
    sort: "updatedAt:desc",
    page: 1,
    pageSize: 16,
  });
  return result.data || [];
}

export async function fetchLatestFollowers() {
  const response = await api.follower.getFollowers({
    sort: "createdAt:desc",
    "pagination[page]": 1,
    "pagination[pageSize]": 16,
    populate: ["avatar"],
  });

  return response.data?.data || [];
}
