import { getClipUrl } from "@/app/lib/clip-url";
import { Clip } from "@/lib/types/strapi-autogenerated";
import { ScrollArea } from "@mantine/core";
import Link from "next/link";

export function ClipSlider({ clips }: { clips: Clip[] }) {
  return (
    <div style={{ overflow: "hidden" }}>
      <ScrollArea type="never" scrollbarSize={0} mt="xl" mx={-32}>
        <div
          style={{
            display: "flex",
            gap: "20px",
            justifyContent: "center",
            minWidth: "max-content",
          }}
        >
          {clips.map((clip) => (
            <Link href={`/shorts/${clip.documentId}`} key={clip.id}>
              <video
                poster={getClipUrl(clip.documentId!, "thumbnail.jpg", clip.path)}
                preload="metadata"
                autoPlay
                muted
                loop
                playsInline
                height={400}
                style={{
                  flexShrink: 0,
                  pointerEvents: "none",
                  borderRadius: "8px",
                }}
              >
                <source
                  src={getClipUrl(clip.documentId!, "preview.mp4", clip.path)}
                  type="video/mp4"
                />
              </video>
            </Link>
          ))}
        </div>
      </ScrollArea>
    </div>
  );
}
