import { ImageSpritePreview } from "@/app/[locale]/(protected)/components/image-sprite-preview";
import { RecordingMenu } from "@/app/[locale]/(protected)/components/recording-menu";
import { FollowerTypeEnum, Recording } from "@/lib/types/strapi-autogenerated";
import {
  Box,
  Button,
  Flex,
  Group,
  SimpleGrid,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { IconBrandSafari, IconChevronRight } from "@tabler/icons-react";
import { getFormatter, getTranslations } from "next-intl/server";
import Link from "next/link";

interface DiscoverSectionProps {
  discoverPromise: Promise<Recording[]>;
}

export async function DiscoverSection({
  discoverPromise,
}: DiscoverSectionProps) {
  const t = await getTranslations("protected.dashboard");
  const format = await getFormatter();
  const recordings = await discoverPromise;

  if (recordings.length === 0) {
    return null;
  }

  return (
    <Stack gap="md">
      <Flex justify="space-between" align="center">
        <Flex gap="xs" align="center">
          <IconBrandSafari size={24} />
          <Title order={2} size="h4">
            {t("discoverSection")}
          </Title>
        </Flex>
        <Link href="/explore">
          <Button
            variant="outline"
            color="gray"
            size="sm"
            rightSection={<IconChevronRight size={16} />}
          >
            {t("browseAll")}
          </Button>
        </Link>
      </Flex>

      <SimpleGrid cols={{ base: 3, sm: 4, md: 8 }} spacing="sm">
        {recordings.map((rec) => (
          <Stack key={rec.documentId} gap="4">
            <Box pos="relative" style={{ opacity: rec.hidden ? 0.5 : 1 }}>
              <ImageSpritePreview
                recording={rec}
                username={rec.follower?.username || ""}
                type={rec.follower?.type || FollowerTypeEnum.Tiktok}
              />
            </Box>

            <Group justify="space-between" align="center">
              <Text size="xs" suppressHydrationWarning>
                {format.dateTime(new Date(rec.createdAt || ""), {
                  dateStyle: "medium",
                  timeStyle: "short",
                })}
              </Text>
              {rec.follower && (
                <RecordingMenu
                  recording={rec}
                  username={rec.follower.username}
                  type={rec.follower.type || FollowerTypeEnum.Tiktok}
                />
              )}
            </Group>
          </Stack>
        ))}
      </SimpleGrid>
    </Stack>
  );
}
