"use client";

import { CountryFlag } from "@/app/[locale]/(protected)/components/country-flag";
import FollowButton from "@/app/[locale]/(protected)/components/follow-button";
import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import { getProfileUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { useUser } from "@/app/providers/user-provider";
import { Follower } from "@/lib/types/strapi-autogenerated";
import { Anchor, Avatar, Card, Group, Stack, Text } from "@mantine/core";
import Image from "next/image";

export function FollowerCard({ follower }: { follower: Follower }) {
  const user = useUser();
  const userFollowers = (user as any)?.followers || [];
  const isFollowing = userFollowers.some(
    (f: any) => f.id === follower.id || f.documentId === follower.documentId,
  );

  return (
    <Card
      padding={16}
      style={{
        background: "rgba(255, 255, 255, 0.02)",
        border: "1px solid rgba(255, 255, 255, 0.06)",
        borderRadius: "16px",
        textAlign: "center",
      }}
    >
      <Stack align="center" gap={8}>
        <Anchor href={getProfileUrl(follower)} underline="never">
          <div style={{ position: "relative", cursor: "pointer" }}>
            <Avatar size={64} radius="xl">
              <Image
                src={generateAvatarUrl(follower.avatar?.url)}
                alt={follower.username || ""}
                width={64}
                height={64}
                quality={75}
              />
            </Avatar>
            <FollowerTypeIcon
              pos="absolute"
              color="transparent"
              type={follower.type}
              top="50%"
              left="50%"
              size={32}
              opacity={0.8}
              style={{ transform: "translate(-50%, -50%)" }}
            />
          </div>
        </Anchor>
        <div>
          <Group gap={4} justify="center">
            <Text fw={600} size="sm" style={{ color: "#f1f5f9" }}>
              {follower.nickname || follower.username}
            </Text>
            {follower.countryCode && (
              <CountryFlag countryCode={follower.countryCode} size={16} />
            )}
          </Group>
          <Text size="xs" style={{ color: "#64748b" }}>
            @{follower.username}
          </Text>
        </div>
        {!isFollowing && (
          <FollowButton
            username={follower.username!}
            type={follower.type}
          />
        )}
      </Stack>
    </Card>
  );
}
