import { Follower } from "@/lib/types/strapi-autogenerated";
import { Flex, SimpleGrid, Stack, Title } from "@mantine/core";
import { IconUsersGroup } from "@tabler/icons-react";
import { getTranslations } from "next-intl/server";
import { FollowerCard } from "./follower-card";

interface LatestFollowersSectionProps {
  followersPromise: Promise<Follower[]>;
}

export async function LatestFollowersSection({
  followersPromise,
}: LatestFollowersSectionProps) {
  const t = await getTranslations("protected.dashboard");
  const latestFollowers = await followersPromise;

  if (latestFollowers.length === 0) {
    return null;
  }

  return (
    <Stack gap="md">
      <Flex gap="xs" align="center">
        <IconUsersGroup size={24} />
        <Title order={2} size="h4">
          {t("newCreators")}
        </Title>
      </Flex>

      <SimpleGrid cols={{ base: 3, sm: 4, md: 6 }} spacing="sm">
        {latestFollowers.map((follower) => (
          <FollowerCard key={follower.documentId} follower={follower} />
        ))}
      </SimpleGrid>
    </Stack>
  );
}
