import { CreatorCard } from "@/app/[locale]/(protected)/components/creator-card";
import { Follower } from "@/lib/types/strapi-autogenerated";
import { Flex, Group, Stack, Title } from "@mantine/core";
import { IconUsersGroup } from "@tabler/icons-react";
import { getTranslations } from "next-intl/server";

interface LatestFollowersSectionProps {
  followersPromise: Promise<Follower[]>;
}

export async function LatestFollowersSection({
  followersPromise,
}: LatestFollowersSectionProps) {
  const t = await getTranslations("protected.dashboard");
  const latestFollowers = await followersPromise;

  if (latestFollowers.length === 0) {
    return null;
  }

  return (
    <Stack gap="md">
      <Flex gap="xs" align="center">
        <IconUsersGroup size={24} />
        <Title order={2} size="h4">
          {t("newCreators")}
        </Title>
      </Flex>

      <Group gap="sm">
        {latestFollowers.map((follower) => (
          <CreatorCard key={follower.documentId} follower={follower} />
        ))}
      </Group>
    </Stack>
  );
}
