"use client";

import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import { getProfileUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { safeRelativeTime } from "@/app/lib/safe-relative-time";
import { Follower } from "@/lib/types/strapi-autogenerated";
import { Anchor, Avatar, Box, Card, Group, Stack, Text } from "@mantine/core";
import { IconVideo } from "@tabler/icons-react";
import { useFormatter, useNow } from "next-intl";
import NextImage from "next/image";
import FollowButton from "./follow-button";
import UnfollowButton from "./unfollow-button";

interface CreatorCardProps {
  follower: Follower;
  width?: number | string;
  isFollowing?: boolean;
  showFollowAction?: boolean;
}

export function CreatorCard({
  follower,
  width = 200,
  isFollowing,
  showFollowAction,
}: CreatorCardProps) {
  const format = useFormatter();
  const now = useNow({ updateInterval: 1000 * 30 });
  const avatarUrl = follower.avatar?.url
    ? generateAvatarUrl(follower.avatar.url)
    : null;

  return (
    <Anchor
      href={getProfileUrl(follower)}
      underline="never"
      style={{ flexShrink: 0 }}
    >
      <Card
        w={width}
        padding={0}
        radius="lg"
        style={{
          background: "rgba(255, 255, 255, 0.03)",
          border: "1px solid rgba(255, 255, 255, 0.08)",
          cursor: "pointer",
          overflow: "hidden",
          position: "relative",
        }}
      >
        <Box
          h={80}
          style={{
            backgroundImage: avatarUrl
              ? `url(${avatarUrl})`
              : "linear-gradient(135deg, #1a1b1e, #2c2e33)",
            backgroundSize: "cover",
            backgroundPosition: "top",
            filter: "brightness(0.6)",
          }}
        />

        {showFollowAction && follower.username && follower.type && (
          <Box
            pos="absolute"
            top={6}
            right={6}
            onClick={(e) => {
              e.preventDefault();
              e.stopPropagation();
            }}
            style={{ zIndex: 2 }}
          >
            {isFollowing ? (
              <UnfollowButton
                username={follower.username}
                type={follower.type}
              />
            ) : (
              <FollowButton
                username={follower.username}
                type={follower.type}
              />
            )}
          </Box>
        )}

        <Stack align="center" mt={-40} gap="sm" pb="md" px="md">
          <Avatar
            size={72}
            radius="xl"
            style={{ border: "3px solid var(--mantine-color-dark-7)" }}
          >
            {avatarUrl && (
              <NextImage
                src={avatarUrl}
                alt={follower.username || ""}
                width={72}
                height={72}
              />
            )}
          </Avatar>

          <Stack gap={2} align="center" w="100%">
            <Group gap={4} align="center" wrap="nowrap">
              <Text fw={700} size="sm" c="white" lineClamp={1}>
                {follower.nickname || follower.username}
              </Text>
              <FollowerTypeIcon
                type={follower.type}
                color="transparent"
                size={16}
                style={{ flexShrink: 0 }}
              />
            </Group>
            <Text size="xs" c="dimmed" ta="center" lineClamp={1}>
              @{follower.username}
            </Text>
          </Stack>

          <Group gap="xs" align="center">
            <IconVideo size={14} color="var(--mantine-color-dimmed)" />
            <Text size="xs" c="dimmed">
              {follower.recordingsCount || 0} videos
            </Text>
          </Group>

          {follower.createdAt && (
            <Text size="xs" c="dimmed" suppressHydrationWarning>
              Added {safeRelativeTime(format, follower.createdAt, { now })}
            </Text>
          )}
        </Stack>
      </Card>
    </Anchor>
  );
}
