"use client";

import { CreatorUpgradeModal } from "@/app/[locale]/(protected)/components/creator-upgrade-modal";
import {
  checkUser,
  PlatformType,
  UserSearchResult,
} from "@/app/actions/check-user";
import { follow } from "@/app/actions/followers";
import { getProfileUrl } from "@/app/components/open-social";
import { parseUsername } from "@/app/lib/parse-username";
import { streamingPlatforms } from "@/app/lib/streaming-platforms";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import {
  Avatar,
  Badge,
  Button,
  Center,
  Flex,
  Group,
  Image,
  Loader,
  Modal,
  Paper,
  SimpleGrid,
  Stack,
  Text,
  TextInput,
  UnstyledButton,
} from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { notifications } from "@mantine/notifications";
import {
  IconArrowLeft,
  IconCheck,
  IconSearch,
  IconUsersPlus,
  IconX,
} from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";

const ALL_PLATFORMS: PlatformType[] = [
  "tiktok",
  "twitch",
  "kick",
  "youtube",
  "afreecatv",
  "bigo",
  "tango",
];

type Step = "search" | "platform" | "result";

interface SearchCreatorModalProps {
  opened: boolean;
  onClose: () => void;
}

export function SearchCreatorModal({
  opened,
  onClose,
}: SearchCreatorModalProps) {
  const t = useTranslations("protected.search");
  const tCommon = useTranslations("protected.common");
  const [upgradeOpened, { open: openUpgrade, close: closeUpgrade }] =
    useDisclosure(false);
  const [query, setQuery] = useState("");
  const [parsedUsername, setParsedUsername] = useState("");
  const [searchResults, setSearchResults] = useState<UserSearchResult[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [searchError, setSearchError] = useState<string | null>(null);
  const [isFollowing, setIsFollowing] = useState(false);
  const [followedUser, setFollowedUser] = useState<UserSearchResult | null>(
    null,
  );
  const [selectedPlatform, setSelectedPlatform] =
    useState<PlatformType | null>(null);
  const [step, setStep] = useState<Step>("search");
  const cancelSearchRef = useRef(false);
  const inputRef = useRef<HTMLInputElement>(null);

  // Reset state when modal opens
  useEffect(() => {
    if (opened) {
      setQuery("");
      setParsedUsername("");
      setSearchResults([]);
      setSearchError(null);
      setSelectedPlatform(null);
      setFollowedUser(null);
      setStep("search");
      setIsSearching(false);
      // Focus input after modal animation
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [opened]);

  const cancelSearch = useCallback(() => {
    cancelSearchRef.current = true;
    setIsSearching(false);
  }, []);

  const executeSearch = async (username: string, platform: PlatformType) => {
    cancelSearchRef.current = false;
    setIsSearching(true);
    setSearchError(null);
    setSearchResults([]);
    setFollowedUser(null);
    setSelectedPlatform(platform);
    setStep("result");

    try {
      const result = await checkUser(username, platform);

      if (cancelSearchRef.current) return;

      if (result.success && result.user) {
        setSearchResults([result.user]);
      } else {
        setSearchError(t("search.notFound"));
      }
    } catch {
      setSearchError(t("search.notFound"));
    } finally {
      setIsSearching(false);
    }
  };

  const handleSubmit = (e?: React.FormEvent) => {
    e?.preventDefault();

    const q = query.trim();
    if (!q) return;

    const parsed = parseUsername(q);
    if (!parsed.username) {
      setSearchError(t("search.parseError"));
      return;
    }

    setParsedUsername(parsed.username);
    setSearchError(null);
    setSearchResults([]);
    setFollowedUser(null);
    setSelectedPlatform(null);

    if (parsed.platform) {
      executeSearch(parsed.username, parsed.platform);
    } else {
      setStep("platform");
    }
  };

  const handlePlatformSelect = (platform: PlatformType) => {
    executeSearch(parsedUsername, platform);
  };

  const handleClose = () => {
    cancelSearch();
    onClose();
  };

  const handleBack = () => {
    cancelSearch();
    setSearchResults([]);
    setSearchError(null);
    setFollowedUser(null);
    if (step === "result") {
      setSelectedPlatform(null);
      setStep("platform");
    } else if (step === "platform") {
      setStep("search");
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  };

  const handleUserSelect = async (user: UserSearchResult) => {
    cancelSearch();
    setSearchResults([user]);
    setIsFollowing(true);


    const result = await follow(user.username, user.type as FollowerTypeEnum);
    setIsFollowing(false);

    if (result.success) {
      setFollowedUser(user);
    } else if (result.error === "MAX_3_FOLLOWERS") {
      openUpgrade();
    } else if (result.error === "MAX_50_FOLLOWERS") {
      notifications.show({
        title: tCommon("follow.errorTitle"),
        message: tCommon("followers.max50Message"),
        color: "red",
      });
    } else if (result.error === "MAX_100_FOLLOWERS") {
      notifications.show({
        title: tCommon("follow.errorTitle"),
        message: tCommon("followers.max100Message"),
        color: "red",
      });
    } else {
      notifications.show({
        title: tCommon("follow.errorTitle"),
        message: result.error,
        color: "red",
      });
    }
  };

  const getPlatformInfo = (platform: string) => {
    return streamingPlatforms.find(
      (p) => p.name.toLowerCase() === platform.toLowerCase(),
    );
  };

  const modalTitle = (() => {
    if (step === "search") {
      return (
        <Text fw={500}>{t("search.enterUsername")}</Text>
      );
    }
    if (step === "platform") {
      return (
        <Group gap="xs">
          <UnstyledButton onClick={handleBack} style={{ display: "flex" }}>
            <IconArrowLeft size={18} />
          </UnstyledButton>
          <Text fw={500}>{t("search.selectPlatform")}</Text>
          <Badge variant="outline" size="sm">
            @{parsedUsername}
          </Badge>
        </Group>
      );
    }
    const platformInfo = selectedPlatform ? getPlatformInfo(selectedPlatform) : null;
    return (
      <Group gap="xs">
        <UnstyledButton onClick={handleBack} style={{ display: "flex" }}>
          <IconArrowLeft size={18} />
        </UnstyledButton>
        {platformInfo && (
          <Image
            src={platformInfo.file}
            alt={platformInfo.name}
            w={20}
            h={20}
            style={{ filter: "brightness(0) invert(1)" }}
          />
        )}
        <Text fw={500}>
          {selectedPlatform ? t(`platforms.${selectedPlatform}`) : ""}
        </Text>
        <Badge variant="outline" size="sm">
          @{parsedUsername}
        </Badge>
      </Group>
    );
  })();

  return (
    <>
      <CreatorUpgradeModal opened={upgradeOpened} onClose={closeUpgrade} />

      <Modal
        opened={opened}
        onClose={handleClose}
        title={modalTitle}
        size="md"
        centered
      >
        <Stack gap="md">
          {step === "search" && (
            <form onSubmit={handleSubmit}>
              <Flex gap="sm">
                <TextInput
                  ref={inputRef}
                  placeholder={t("search.enterUsername")}
                  value={query}
                  onChange={(e) => setQuery(e.currentTarget.value)}
                  onPaste={(e) => {
                    const text = e.clipboardData.getData("text");
                    if (text?.trim()) {
                      e.preventDefault();
                      setQuery(text);
                      const parsed = parseUsername(text);
                      if (parsed.username) {
                        setParsedUsername(parsed.username);
                        if (parsed.platform) {
                          executeSearch(parsed.username, parsed.platform);
                        } else {
                          setStep("platform");
                        }
                      }
                    }
                  }}
                  leftSection={<IconSearch size={16} />}
                  rightSection={
                    query ? (
                      <IconX
                        size={14}
                        style={{ cursor: "pointer" }}
                        onClick={() => setQuery("")}
                      />
                    ) : null
                  }
                  size="sm"
                  radius="md"
                  style={{ flex: 1 }}
                />
                <Button
                  type="submit"
                  size="sm"
                  radius="md"
                  disabled={!query.trim()}
                  leftSection={<IconSearch size={14} />}
                >
                  {t("search.submitButton")}
                </Button>
              </Flex>
              {searchError && (
                <Text size="sm" c="red" mt="xs">
                  {searchError}
                </Text>
              )}
            </form>
          )}

          {step === "platform" && (
            <SimpleGrid cols={3} spacing="sm">
              {ALL_PLATFORMS.map((platform) => {
                const info = getPlatformInfo(platform);
                const isSelected = selectedPlatform === platform;
                return (
                  <UnstyledButton
                    key={platform}
                    onClick={() => handlePlatformSelect(platform)}
                    style={(theme) => ({
                      padding: theme.spacing.sm,
                      borderRadius: theme.radius.md,
                      border: `1px solid ${
                        isSelected
                          ? "var(--mantine-color-green-6)"
                          : "var(--mantine-color-dark-4)"
                      }`,
                      backgroundColor: isSelected
                        ? "rgba(27, 147, 69, 0.15)"
                        : "transparent",
                      textAlign: "center",
                    })}
                  >
                    <Stack gap={4} align="center">
                      {info && (
                        <Image
                          src={info.file}
                          alt={info.name}
                          w={24}
                          h={24}
                          style={{ filter: "brightness(0) invert(1)" }}
                        />
                      )}
                      <Text size="xs">{t(`platforms.${platform}`)}</Text>
                    </Stack>
                  </UnstyledButton>
                );
              })}
            </SimpleGrid>
          )}

          {step === "result" && (
            <>
              {isSearching && (
                <Center py="md">
                  <Loader size="sm" />
                </Center>
              )}

              {searchError && !isSearching && (
                <Text size="sm" c="red" ta="center">
                  {searchError}
                </Text>
              )}

              {searchResults.map((user) => {
                const isFollowed =
                  followedUser?.username === user.username &&
                  followedUser?.type === user.type;

                return (
                  <Paper
                    key={`${user.type}-${user.username}`}
                    p="sm"
                    radius="md"
                    bg="gray.9"
                    style={{
                      cursor: isFollowed ? "default" : "pointer",
                    }}
                    onClick={
                      !isFollowed && !isFollowing
                        ? () => handleUserSelect(user)
                        : undefined
                    }
                  >
                    <Group wrap="nowrap">
                      <Avatar
                        src={`/api/image/${user.avatar}`}
                        alt={user.nickname}
                        size={48}
                      />
                      <div style={{ flex: 1 }}>
                        <Text fw={500} size="sm">
                          {user.nickname}
                        </Text>
                        <Text size="xs" c="dimmed">
                          @{user.username}
                        </Text>
                      </div>
                      {isFollowed ? (
                        <Badge
                          color="green"
                          variant="filled"
                          size="lg"
                          leftSection={<IconCheck size={14} />}
                        >
                          {t("actions.successTitle")}
                        </Badge>
                      ) : (
                        <Badge
                          variant="filled"
                          size="lg"
                          leftSection={<IconUsersPlus size={14} />}
                          style={{ pointerEvents: "none" }}
                        >
                          {t("actions.follow")}
                        </Badge>
                      )}
                    </Group>
                    {isFollowed && (
                      <Center mt="xs">
                        <Button
                          component={Link}
                          href={getProfileUrl(user as never)}
                          variant="subtle"
                          size="compact-sm"
                        >
                          {t("actions.viewPage")}
                        </Button>
                      </Center>
                    )}
                  </Paper>
                );
              })}
            </>
          )}
        </Stack>
      </Modal>
    </>
  );
}
