"use client";

import { unfollow } from "@/app/actions/followers";
import { useInvalidateRecordings } from "@/app/hooks/use-invalidate-recordings";
import { useUser } from "@/app/providers/user-provider";
import { FollowRequestBody } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Tooltip } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconCheck, IconHeartFilled } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { UnfollowUpgradeModal } from "./unfollow-upgrade-modal";

export default function UnfollowButton({
  username,
  type,
  onSuccess,
}: FollowRequestBody & { onSuccess?: () => void }) {
  const [isPending, startTransition] = useTransition();
  const [upgradeOpened, setUpgradeOpened] = useState(false);
  const t = useTranslations("protected.common");
  const user = useUser();
  const invalidateRecordings = useInvalidateRecordings();
  const router = useRouter();

  const isFreeUser = user?.role?.type === "authenticated";

  const handleClick = () => {
    if (isFreeUser) {
      setUpgradeOpened(true);
      return;
    }

    startTransition(async () => {
      await unfollow({ username, type });
      invalidateRecordings();
      router.refresh();

      notifications.show({
        title: t("unfollow.successTitle"),
        message: username
          ? t("unfollow.successMessage", { username })
          : t("unfollow.successMessageGeneric"),
        color: "green",
        icon: <IconCheck size={16} />,
      });
      onSuccess?.();
    });
  };

  return (
    <>
      <Tooltip label={t("unfollow.tooltip")}>
        <ActionIcon
          variant="subtle"
          size="lg"
          color="red"
          type="button"
          onClick={handleClick}
          loading={isPending}
        >
          <IconHeartFilled />
        </ActionIcon>
      </Tooltip>
      <UnfollowUpgradeModal
        opened={upgradeOpened}
        onClose={() => setUpgradeOpened(false)}
      />
    </>
  );
}
